In [1]:
!pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 640.0 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 785.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.4/12.6 MB 8.9 MB/s eta 0:00:02
   --- ------------------------------------ 1.1/12.6 MB 12.1 MB/s eta 0:00:01
   ----- ---------------------------------- 1.8/12.6 MB 13.0 MB/s eta 0:00:01
   --------- ------------------------------ 3.1/12.6 MB 17.9 MB/s eta 0:00:01
   --------------- ------------------------ 4.9/12.6 MB 20.9 MB/s eta 0:00:01
   ----------------------- ---------------- 7.5/12.6 MB 26.5 MB/s eta 0:00:01
   ---------------------------------- ----- 10.9/12.6 MB 38.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 50.4 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 40.9 MB/s eta 0:


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [4]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [6]:
np.arange(1, 6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.ones((3, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [11]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [12]:
np.full(5, 4, dtype = "float")

array([4., 4., 4., 4., 4.])

In [21]:
arr_2d = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])

In [15]:
arr_3d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]],
    [[2, 4, 6, 8], [10, 12, 14, 16]],
    [[1, 3, 5, 7], [9, 11, 13, 15]]
])

In [16]:
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 2  4  6  8]
  [10 12 14 16]]

 [[ 1  3  5  7]
  [ 9 11 13 15]]]


In [17]:
print(arr_3d.shape)

(3, 2, 4)


In [18]:
print(arr_3d.size)

24


In [20]:
print(arr_3d.ndim)

3


In [22]:
print(arr_2d.shape)
print(arr_2d.size)
print(arr_2d.ndim)

(2, 5)
10
2


In [23]:
print(arr_2d)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
