In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])

In [4]:
print(arr_1d[0])

1


In [5]:
print(arr_1d[-1])

5


In [6]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 7],
                   [6, 8, 9],
                   [11, 17, 19]])

In [7]:
print(arr_2d)

[[ 1  2  3]
 [ 4  5  7]
 [ 6  8  9]
 [11 17 19]]


In [10]:
print(arr_2d[1][1])
print(arr_2d[1, 1])

5
5


In [11]:
print(arr_2d[3, -1])

19


In [12]:
print(arr_2d[1, 1:3])

[5 7]


In [14]:
print(arr_2d[1:3, 1:3])

[[5 7]
 [8 9]]


In [15]:
print(arr_2d)

[[ 1  2  3]
 [ 4  5  7]
 [ 6  8  9]
 [11 17 19]]


In [18]:
print(arr_2d[0:4, 0])

[ 1  4  6 11]


In [20]:
arr = np.array([0, 1, -4, 9, -16, 25])

In [21]:
np.abs(arr)

array([ 0,  1,  4,  9, 16, 25])

In [22]:
np.square(arr)

array([  0,   1,  16,  81, 256, 625])

In [23]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 1.83156389e-02, 8.10308393e+03,
       1.12535175e-07, 7.20048993e+10])

In [24]:
arr = np.array([1.15, 2.26, 3.4])

In [25]:
np.round(arr)

array([1., 2., 3.])

In [26]:
np.round(arr, 1)

array([1.2, 2.3, 3.4])

In [27]:
arr_1 = np.arange(5)
arr_2 = np.arange(1, 10, step = 2)

In [28]:
print(arr_1)
print(arr_2)

[0 1 2 3 4]
[1 3 5 7 9]


In [29]:
arr_1 + arr_2

array([ 1,  4,  7, 10, 13])

In [30]:
arr_1 * arr_2

array([ 0,  3, 10, 21, 36])

In [31]:
np.add(arr_1, arr_2)

array([ 1,  4,  7, 10, 13])

In [32]:
arr_2d_3x3 = np.array([[1, 4, 7],
                       [2, 5, 8],
                       [3, 6, 9]
])

In [33]:
arr_1d_3 = np.array([1, 0, -1])

In [34]:
arr_2d_3x3 + arr_1d_3

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])