In [1]:
import numpy as np

In [2]:
arr_1d = np.arange(8)

In [4]:
arr_1d.reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr_1d.reshape(4, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
arr_2d = arr_1d.reshape(4, -1)

In [9]:
arr_2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
arr_2d.reshape(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
arr_2d.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
arr_2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
arr_2d.transpose()

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])